/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AiLogsRouteImport } from './routes/ai-logs'
import { Route as AskRouteImport } from './routes/ask'
import { Route as CaptureRouteImport } from './routes/capture'
import { Route as GapsRouteImport } from './routes/gaps'
import { Route as GraphRouteImport } from './routes/graph'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as WikiIndexRouteImport } from './routes/wiki.index'
import { Route as WikiSlugRouteImport } from './routes/wiki.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api.auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiLogsRoute = AiLogsRouteImport.update({
  id: '/ai-logs',
  path: '/ai-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const CaptureRoute = CaptureRouteImport.update({
  id: '/capture',
  path: '/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const GapsRoute = GapsRouteImport.update({
  id: '/gaps',
  path: '/gaps',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphRoute = GraphRouteImport.update({
  id: '/graph',
  path: '/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiSlugRoute = WikiSlugRouteImport.update({
  id: '/wiki/$slug',
  path: '/wiki/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/ask': typeof AskRoute
  '/capture': typeof CaptureRoute
  '/gaps': typeof GapsRoute
  '/graph': typeof GraphRoute
  '/signin': typeof SigninRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/ask': typeof AskRoute
  '/capture': typeof CaptureRoute
  '/gaps': typeof GapsRoute
  '/graph': typeof GraphRoute
  '/signin': typeof SigninRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-logs': typeof AiLogsRoute
  '/ask': typeof AskRoute
  '/capture': typeof CaptureRoute
  '/gaps': typeof GapsRoute
  '/graph': typeof GraphRoute
  '/signin': typeof SigninRoute
  '/wiki/$slug': typeof WikiSlugRoute
  '/wiki/': typeof WikiIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-logs'
    | '/ask'
    | '/capture'
    | '/gaps'
    | '/graph'
    | '/signin'
    | '/wiki/$slug'
    | '/wiki/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-logs'
    | '/ask'
    | '/capture'
    | '/gaps'
    | '/graph'
    | '/signin'
    | '/wiki/$slug'
    | '/wiki'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/ai-logs'
    | '/ask'
    | '/capture'
    | '/gaps'
    | '/graph'
    | '/signin'
    | '/wiki/$slug'
    | '/wiki/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiLogsRoute: typeof AiLogsRoute
  AskRoute: typeof AskRoute
  CaptureRoute: typeof CaptureRoute
  GapsRoute: typeof GapsRoute
  GraphRoute: typeof GraphRoute
  SigninRoute: typeof SigninRoute
  WikiSlugRoute: typeof WikiSlugRoute
  WikiIndexRoute: typeof WikiIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-logs': {
      id: '/ai-logs'
      path: '/ai-logs'
      fullPath: '/ai-logs'
      preLoaderRoute: typeof AiLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capture': {
      id: '/capture'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof CaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gaps': {
      id: '/gaps'
      path: '/gaps'
      fullPath: '/gaps'
      preLoaderRoute: typeof GapsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graph': {
      id: '/graph'
      path: '/graph'
      fullPath: '/graph'
      preLoaderRoute: typeof GraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$slug': {
      id: '/wiki/$slug'
      path: '/wiki/$slug'
      fullPath: '/wiki/$slug'
      preLoaderRoute: typeof WikiSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiLogsRoute: AiLogsRoute,
  AskRoute: AskRoute,
  CaptureRoute: CaptureRoute,
  GapsRoute: GapsRoute,
  GraphRoute: GraphRoute,
  SigninRoute: SigninRoute,
  WikiSlugRoute: WikiSlugRoute,
  WikiIndexRoute: WikiIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
